version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NAME=APP
      - database_name='db'
      
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
